### ISSUE TITLE
[Feature Request] Multiple thread URLs

### ISSUE THREAD

**Issue by dermalikmann** [cardoso-neto/archive-chan#2]
It would be nice, if I could add multiple threads to download at once. Would also be wild together with #1

**Comment by cardoso-neto** [comment]
Like a list of URLs on the CLI or with a .txt file with an URL on each line?

**Comment by cardoso-neto** [comment]
So this is online now.
Check the https://github.com/cardoso-neto/archive-chan#batch-download-handpicked-threads example on the README for more info.
I'm closing this, but feel free to open more issues as needed.

**Comment by cardoso-neto** [comment]
![image](https://user-images.githubusercontent.com/46901498/124317933-4e265880-db4e-11eb-95c6-b9f78f7ada54.png)
fyi this is what the .txt should look like.
